name = "vote-sandiego48-com"
compatibility_date = "2025-04-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "vote-sandiego48-com"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "vote-sandiego48-com"
