name = "vote-sandiego48-com"
compatibility_date = "2025-04-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "vote-sandiego48-com"
database_id = "f44fa4cf-711a-4618-9469-86e78d44aa34"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "vote-sandiego48-com"
